"""Writes tokens.css and tokens.json, nixkeeper's colours and fonts, into a
folder (default: assets/brand/).

    python3 scripts/brand/tokens.py [folder]

Every colour comes from the NixOS guide's tint recipe (OKLCH lightness 0.95 to
0.15, with its chroma per step): the guide's own accents at their hues, and
nixkeeper's brand violet and mauve at theirs. See assets/brand/BRAND.md for
what each role means and how the page uses it.
"""

import json
import os
import sys

from geometry import oklch_hex

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = (
    sys.argv[1]
    if len(sys.argv) > 1
    else os.path.join(HERE, "..", "..", "assets", "brand")
)

STEPS = [95, 85, 75, 65, 55, 45, 35, 25, 15]
CHROMA = [None, 0.07, 0.12, 0.12, 0.11, 0.09, 0.07, 0.05, 0.03]  # the guide's


def ramp(hue, cmax=0.12, c95=0.02):
    """The guide's tints at a hue: {"l95": hex, ..., "l15": hex}."""
    return {
        f"l{step}": oklch_hex(step / 100, (c95 if c is None else c) * cmax / 0.12, hue)
        for step, c in zip(STEPS, CHROMA, strict=True)
    }


ramps = {
    "violet": ramp(288),  # brand
    "mauve": ramp(313, cmax=0.09),  # brand, the mark's light end
    "green": ramp(152, c95=0.03),  # Zambian Green
    "orange": ramp(54),  # Persian Orange
    "pink": ramp(16),  # Norwegian Pink
    "gold": ramp(90, c95=0.03),  # Indian Gold
    "neutral": {f"l{s}": oklch_hex(s / 100, 0, 0) for s in STEPS},
}

brand = {
    "violet": oklch_hex(0.50, 0.12, 288),  # the mark's centre and 25% stop
    "violet-shade": oklch_hex(0.45, 0.10, 288),  # the mark's 0% stop
    "mauve": oklch_hex(0.75, 0.09, 313),  # the mark's 100% stop
}

# The page's meanings, each in one of the ramps. Light theme: dots at L65,
# text at L45 (the L75 accents aren't readable as text on white), badges at
# L55 with white text, backgrounds at L95. Dark theme: L75 for all three,
# backgrounds at L25.
ROLES = {
    "ok": "green",  # up to date
    "outdated": "orange",  # outdated, a new release
    "failed": "pink",  # failed, not in nixpkgs, vulnerable
    "warn": "gold",  # can't update, marked broken
    "merged": "violet",  # on master
    "link": "violet",  # links and key UI
}


def role(r):
    return {
        "light": {
            "fill": r["l65"],
            "text": r["l45"],
            "badge": r["l55"],
            "bg": r["l95"],
        },
        "dark": {"fill": r["l75"], "text": r["l75"], "badge": r["l65"], "bg": r["l25"]},
    }


roles = {name: role(ramps[r]) for name, r in ROLES.items()}
fonts = {
    "ui": '"Instrument Sans", system-ui, sans-serif',  # the page, and the wordmark
    "mono": '"JetBrains Mono", ui-monospace, monospace',  # versions
}

os.makedirs(OUT, exist_ok=True)
with open(os.path.join(OUT, "tokens.json"), "w") as f:
    json.dump(
        {"brand": brand, "ramps": ramps, "roles": roles, "fonts": fonts}, f, indent=2
    )
    f.write("\n")

css = ["/* Generated by scripts/brand/tokens.py: edit that, not this. */", ":root {"]
css += [f"  --nk-{k}: {v};" for k, v in brand.items()]
for name, r in ramps.items():
    css += [f"  --nk-{name}-{step}: {v};" for step, v in r.items()]
for name, themes in roles.items():
    css += [f"  --nk-{name}-{k}: {v};" for k, v in themes["light"].items()]
css += [f"  --nk-font-{k}: {v};" for k, v in fonts.items()]
css += ["}", "@media (prefers-color-scheme: dark) {", "  :root {"]
for name, themes in roles.items():
    css += [f"    --nk-{name}-{k}: {v};" for k, v in themes["dark"].items()]
css += ["  }", "}"]
with open(os.path.join(OUT, "tokens.css"), "w") as f:
    f.write("\n".join(css) + "\n")

print(f"tokens: {len(ramps)} ramps, {len(roles)} roles")
